
export const FETCH_USER_DETAIL_REQUEST = 'FETCH_USER_DETAIL_REQUEST'
export const FETCH_USER_DETAIL_FAILURE = 'FETCH_USER_DETAIL_FAILURE'
export const FETCH_USER_DETAIL_SUCCESS = 'FETCH_USER_DETAIL_SUCCESS'